### ISSUE TITLE
`run --blkio-weight` results in a panic

### ISSUE THREAD

**Issue by davidhsingyuchen** [containerd/nerdctl#1514]
### Description

If `--blkio-weight` is given to `nerdctl run`, `nerdctl` panics.

We may need to change this line:

https://github.com/containerd/nerdctl/blob/c00780a1f5b905b09812722459c54936c9e070e6/pkg/infoutil/infoutil.go#L249

to:

```go
info := &dockercompat.Info{}
```

so that `info` won't be a `nil` pointer on the next line:

https://github.com/containerd/nerdctl/blob/c00780a1f5b905b09812722459c54936c9e070e6/pkg/infoutil/infoutil.go#L250

I'm happy to PR it, and I just want to make sure I'm not missing anything.

Re. why it's not caught by existing tests, my guess is that `BlockIOWeight` does not have unit tests because it's platform-dependent, and re. integration tests, `TestRunBlkioWeightCgroupV2` seems to be skipped because `bfq` module is not loaded. I only checked [a random recent workflow run](https://github.com/containerd/nerdctl/actions/runs/3478937000/jobs/5827626977), so I could be missing something.

### Steps to reproduce the issue

```sh
lima nerdctl run --name ctr1 --blkio-weight 300 -w /sys/fs/cgroup alpine sleep infinity
```

#### Received

```sh
➜  ~ lima nerdctl run --name ctr1 --blkio-weight 300 -w /sys/fs/cgroup alpine sleep infinity
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa69f08]

goroutine 1 [running]:
github.com/containerd/nerdctl/pkg/infoutil.BlockIOWeight({0xdd21ec, 0x7})
	/go/src/github.com/containerd/nerdctl/pkg/infoutil/infoutil.go:250 +0x28
main.generateCgroupOpts(0xc5fd00?, {0x40002f81c0, 0x40})
	/go/src/github.com/containerd/nerdctl/cmd/nerdctl/run_cgroup_linux.go:244 +0x1584
main.setPlatformOptions({0x1100978, 0x40004c6000}, {0x400000e040?, 0x1?, 0x40?}, 0x0?, 0x0?, {0x40002f81c0, 0x40})
	/go/src/github.com/containerd/nerdctl/cmd/nerdctl/run_linux.go:72 +0x294
main.createContainer(0x0?, {0x1100978, 0x40004c6000}, 0x0?, {0x40002230e0?, 0x0?, 0x0?}, {0x0, 0x0}, 0x0, ...)
	/go/src/github.com/containerd/nerdctl/cmd/nerdctl/run.go:435 +0x2a0
main.runAction(0x400013a900, {0x40002230e0, 0x3, 0x9})
	/go/src/github.com/containerd/nerdctl/cmd/nerdctl/run.go:300 +0x12c
github.com/spf13/cobra.(*Command).execute(0x400013a900, {0x400003a0d0, 0x9, 0x9})
	/go/pkg/mod/github.com/spf13/cobra@v1.6.0/command.go:916 +0x5e0
github.com/spf13/cobra.(*Command).ExecuteC(0x400013a300)
	/go/pkg/mod/github.com/spf13/cobra@v1.6.0/command.go:1040 +0x360
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.6.0/command.go:968
main.xmain()
	/go/src/github.com/containerd/nerdctl/cmd/nerdctl/main.go:125 +0xc4
main.main()
	/go/src/github.com/containerd/nerdctl/cmd/nerdctl/main.go:108 +0x1c
```

#### Expected

The container should be run successfully with the specified `--blkio-weight`.

### What version of nerdctl are you using?

```sh
➜  ~ lima nerdctl version
Client:
 Version:	v1.0.0
 OS/Arch:	linux/arm64
 Git commit:	c00780a1f5b905b09812722459c54936c9e070e6
 buildctl:
  Version:	v0.10.5
  GitCommit:	bc26045116045516ff2427201abd299043eaf8f7

Server:
 containerd:
  Version:	v1.6.8
  GitCommit:	9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc:
  Version:	1.1.4
  GitCommit:	v1.1.4-0-g5fd4c4d1
```

### Are you using a variant of nerdctl? (e.g., Rancher Desktop)

Lima

### Host information

```sh
➜  ~ lima nerdctl info
Client:
 Namespace:	default
 Debug Mode:	false

Server:
 Server Version: v1.6.8
 Storage Driver: overlayfs
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Log: fluentd journald json-file syslog
  Storage: native overlayfs stargz fuse-overlayfs
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
  rootless
 Kernel Version: 5.15.0-52-generic
 Operating System: Ubuntu 22.04.1 LTS
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 3.816GiB
 Name: lima-default
 ID: a928eae4-cc94-427b-9e85-bcae448db4bd

WARNING: AppArmor profile "nerdctl-default" is not loaded.
         Use 'sudo nerdctl apparmor load' if you prefer to use AppArmor with rootless mode.
         This warning is negligible if you do not intend to use AppArmor.
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

**Comment by yankay** [comment]
HI @davidhsingyuchen, it has been fixed :-)
