### ISSUE TITLE
panic: provided file is not a console

### ISSUE THREAD

**Issue by apostasie** [containerd/nerdctl#3297]
### Description

Likely while mistakenly starting a container with `-ti` on the CI.

We probably want to do better than a panic.

```
panic: provided file is not a console
goroutine 1 [running]:
github.com/containerd/console.Current()
	/home/runner/go/pkg/mod/github.com/containerd/console@v1.0.4/console.go:80 +0x94
github.com/containerd/nerdctl/v2/pkg/cmd/container.generateExecProcessSpec({_, _}, _, {_, _}, {_, _, _}, {{0x0, 0x0, ...}, ...})
	/home/runner/work/nerdctl/nerdctl/pkg/cmd/container/exec.go:167 +0x3ee
github.com/containerd/nerdctl/v2/pkg/cmd/container.execActionWithContainer({_, _}, _, {_, _}, {_, _, _}, {{0x0, 0x0, ...}, ...})
	/home/runner/work/nerdctl/nerdctl/pkg/cmd/container/exec.go:63 +0x7e
github.com/containerd/nerdctl/v2/pkg/cmd/container.Exec.func1({0x13ec170?, 0xc0003c8500?}, {{0x13f48d8, 0xc0005ec2a0}, {0x7ffc44d0f6ca, 0x1a}, 0x0, 0x1})
	/home/runner/work/nerdctl/nerdctl/pkg/cmd/container/exec.go:49 +0x11e
github.com/containerd/nerdctl/v2/pkg/idutil/containerwalker.(*ContainerWalker).Walk(0xc00051b880, {0x13ec170, 0xc0003c8500}, {0x7ffc44d0f6ca, 0x1a})
	/home/runner/work/nerdctl/nerdctl/pkg/idutil/containerwalker/containerwalker.go:69 +0x347
github.com/containerd/nerdctl/v2/pkg/cmd/container.Exec({_, _}, _, {_, _, _}, {{0x0, 0x0, {0x12305bc, 0x1f}, ...}, ...})
	/home/runner/work/nerdctl/nerdctl/pkg/cmd/container/exec.go:53 +0x165
main.execAction(0xc000476608, {0xc00007f260, 0x5, 0x6})
	/home/runner/work/nerdctl/nerdctl/cmd/nerdctl/container_exec.go:141 +0x33c
github.com/spf13/cobra.(*Command).execute(0xc000476608, {0xc00003e0a0, 0x6, 0x6})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:985 +0xaca
github.com/spf13/cobra.(*Command).ExecuteC(0xc00039d808)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1117 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1041
main.xmain()
	/home/runner/work/nerdctl/nerdctl/cmd/nerdctl/main.go:137 +0x8f
main.main()
	/home/runner/work/nerdctl/nerdctl/cmd/nerdctl/main.go:120 +0x13
```

### Steps to reproduce the issue

na

### Describe the results you received and expected

na

### What version of nerdctl are you using?

main

### Are you using a variant of nerdctl? (e.g., Rancher Desktop)

None

**Comment by apostasie** [comment]
FWIW:

* https://github.com/containerd/console/blob/main/console.go#L80
* https://github.com/containerd/nerdctl/blob/main/pkg/cmd/container/exec.go#L167

**Comment by apostasie** [comment]
Here is a simple repro:

```
nerdctl --debug-full=true run -ti debian echo lo </dev/null |& cat
```

**Comment by apostasie** [comment]
Here is a repro for the compose one as seen on usernetes:

compose.yaml
```
services:
  web:
    image: node
    command: ["sleep", "Inf"]
```


```
nerdctl compose up -d
nerdctl compose exec web echo lol </dev/null |& cat
```

**Comment by apostasie** [comment]
FWIW, docker exec gives:
```
docker exec -ti 7e36c314c3bd59ba590035fc6c1c4d96a0e1a4981ae0e02f7e6bdaddfc0d8b92 echo lol </dev/null |& cat
the input device is not a TTY
```

While docker compose exec will just run with it:
```
docker compose exec web echo lol </dev/null |& cat

lol
```

@AkihiroSuda @fahedouch do you have an idea on how we should handle this?

**Comment by alitvak69** [comment]
It also happens when run -t in systemd unit.

**Comment by apostasie** [comment]
> It also happens when run -t in systemd unit.

Did you test with the latest RC?
