### ISSUE TITLE
nerdctl images filter panic

### ISSUE THREAD

**Issue by apostasie** [containerd/nerdctl#3467]
### Description

```
nerdctl images --filter before=whatever
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/containerd/nerdctl/v2/pkg/cmd/image.List.FilterByCreatedAt.func6({0x0, 0x0, 0x0})
	/home/dmp.linux/downloads/nerdctl/pkg/imgutil/filtering.go:153 +0x394
github.com/containerd/nerdctl/v2/pkg/imgutil.ApplyFilters({0x0?, 0x1?, 0x40003de140?}, {0x40000c2160, 0x1, 0x0?})
	/home/dmp.linux/downloads/nerdctl/pkg/imgutil/filtering.go:130 +0x54
github.com/containerd/nerdctl/v2/pkg/cmd/image.List({0xf70458, 0x40003de140}, 0x400006d100, {0x40004fbf50, 0x1, 0x1}, {0x0, 0x0, 0x0})
	/home/dmp.linux/downloads/nerdctl/pkg/cmd/image/list.go:102 +0x4b8
github.com/containerd/nerdctl/v2/pkg/cmd/image.ListCommandHandler({_, _}, _, {{0xf62760, 0x40000c2058}, {0x0, 0x0, {0xdace72, 0x1f}, {0xd87d92, ...}, ...}, ...})
	/home/dmp.linux/downloads/nerdctl/pkg/cmd/image/list.go:51 +0x48
github.com/containerd/nerdctl/v2/cmd/nerdctl/image.imagesAction(0x40004a3508, {0x40003a9d20?, 0x0?, 0x2?})
	/home/dmp.linux/downloads/nerdctl/cmd/nerdctl/image/image_list.go:145 +0x124
github.com/spf13/cobra.(*Command).execute(0x40004a3508, {0x40000d60e0, 0x2, 0x2})
	/home/dmp.linux/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:985 +0x834
github.com/spf13/cobra.(*Command).ExecuteC(0x40003ad208)
	/home/dmp.linux/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1117 +0x344
github.com/spf13/cobra.(*Command).Execute(...)
	/home/dmp.linux/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1041
main.xmain()
	/home/dmp.linux/downloads/nerdctl/cmd/nerdctl/main.go:144 +0xb4
main.main()
	/home/dmp.linux/downloads/nerdctl/cmd/nerdctl/main.go:127 +0x1c
```

Glancing at https://github.com/containerd/nerdctl/blob/main/pkg/imgutil/filtering.go#L153

@AkihiroSuda v2 milestone?

Anyone wants to PR this?
Should be straightforward.

### Steps to reproduce the issue

na

### Describe the results you received and expected

na

### What version of nerdctl are you using?

main

### Are you using a variant of nerdctl? (e.g., Rancher Desktop)

None

**Comment by apostasie** [comment]
Whoever takes it should also look at https://github.com/containerd/nerdctl/blob/main/pkg/imgutil/filtering.go#L166

**Comment by apostasie** [comment]
@austinvazquez would you be able to fix it ^ - if you have free cycles?

**Comment by austinvazquez** [comment]
Thanks @apostasie for the tag. Good catch. The fix proposed by @xyz-li looks good to me.

**Comment by apostasie** [comment]
> Thanks [@apostasie](https://github.com/apostasie) for the tag. Good catch. The fix proposed by [@xyz-li](https://github.com/xyz-li) looks good to me.

Thanks @austinvazquez ! And thanks @xyz-li for the fast turnaround on this!
