### ISSUE TITLE
build panic

### ISSUE THREAD

**Issue by apostasie** [containerd/nerdctl#3481]
### Description

Probably buildctl crashing.

### Steps to reproduce the issue

`nerdctl build --platform=linux/amd64,linux/arm64 -f /tmp/Dockerfile .`

### Describe the results you received and expected

```
[+] Building 0.0s (0/1)
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x6d0d88]

goroutine 26 [running]:
github.com/moby/buildkit/frontend/gateway/grpcclient.convertRef({0xc091a0?, 0x0})
	/src/frontend/gateway/grpcclient/client.go:99 +0x48
github.com/moby/buildkit/frontend/gateway/grpcclient.(*grpcClient).Run.func1()
	/src/frontend/gateway/grpcclient/client.go:131 +0x824
github.com/moby/buildkit/frontend/gateway/grpcclient.(*grpcClient).Run(0x400039a880, {0xc074d0, 0x4000402230}, 0x40001480e0)
	/src/frontend/gateway/grpcclient/client.go:249 +0x3f8
github.com/moby/buildkit/client.(*Client).Build.func2({0x4000424101, 0x19}, 0x400039a280, 0x0?)
	/src/client/build.go:58 +0x30c
github.com/moby/buildkit/client.(*Client).solve.func3()
	/src/client/solve.go:296 +0x54
golang.org/x/sync/errgroup.(*Group).Go.func1()
	/src/vendor/golang.org/x/sync/errgroup/errgroup.go:78 +0x58
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 22
	/src/vendor/golang.org/x/sync/errgroup/errgroup.go:75 +0x98
FATA[0000] no image was built
```

### What version of nerdctl are you using?

main

### Are you using a variant of nerdctl? (e.g., Rancher Desktop)

None

**Comment by apostasie** [comment]
> Could you report to https://github.com/moby/buildkit/issues

Yes - looking into it now.

**Comment by apostasie** [comment]
Done.

https://github.com/moby/buildkit/issues/5379

**Comment by apostasie** [comment]
Fixed upstream.
Will apparently ship with buildkit v0.17.0
