### ISSUE TITLE
nerdctl test error 

### ISSUE THREAD

**Issue by ningmingxiao** [containerd/nerdctl#385]
I use 
nerdctl run -it --rm  --privileged=true -v test-integration 
error is：

=== RUN   TestRunHostLookup
    run_network_test.go:115: resolving "c1-in-n0" in container "c0-in-n0" (should success: true)
    run_network_test.go:115: resolving "c1-in-n0.n0" in container "c0-in-n0" (should success: true)
    run_network_test.go:115: resolving "c1-in-n0-foobar" in container "c0-in-n0" (should success: true)
    run_network_test.go:115: resolving "c1-in-n0-foobar.n0" in container "c0-in-n0" (should success: true)
    run_network_test.go:118: assertion failed:
        Command:  /usr/local/bin/nerdctl --namespace=nerdctl-test exec c0-in-n0 wget -qO- http://c1-in-n0-foobar.n0
        ExitCode: 0
        Stdout:
        Stderr:

        Failures:
        Expected stdout to contain "<title>Welcome to nginx!</title>"
--- FAIL: TestRunHostLookup (6.42s)
=== RUN   TestRunPort
=== RUN   TestRunPort/{listenIP:[0_0_0_0_0_0_0_0_0_0_255_255_127_0_0_1]_connectIP:[0_0_0_0_0_0_0_0_0_0_255_255_127_0_0_1]_hostPort:8080_containerPort:80_        connectURLPort:8080_runShouldSuccess:true_err:}
    run_network_test.go:301: pFlag="127.0.0.1:8080:80", connectURL="http://127.0.0.1:8080"
    run_network_test.go:318: assertion failed: error is not nil: error after 30 attempts: Get "http://127.0.0.1:8080": context deadline exceeded (Client.        Timeout exceeded while awaiting headers)
=== RUN   TestRunPort/{listenIP:[10_4_0_28]_connectIP:[10_4_0_28]_hostPort:8080_containerPort:80_connectURLPort:8080_runShouldSuccess:true_err:}
    run_network_test.go:301: pFlag="10.4.0.28:8080:80", connectURL="http://10.4.0.28:8080"
    run_network_test.go:318: assertion failed: error is not nil: error after 30 attempts: Get "http://10.4.0.28:8080": context deadline exceeded (Client.        Timeout exceeded while awaiting headers)
=== RUN   TestRunPort/{listenIP:[10_4_0_28]_connectIP:[0_0_0_0_0_0_0_0_0_0_255_255_127_0_0_1]_hostPort:8080_containerPort:80_connectURLPort:8080_runShoul        dSuccess:true_err:connection_refused}
    run_network_test.go:301: pFlag="10.4.0.28:8080:80", connectURL="http://127.0.0.1:8080"
=== RUN   TestRunPort/{listenIP:[0_0_0_0_0_0_0_0_0_0_255_255_127_0_0_1]_connectIP:[10_4_0_28]_hostPort:8080_containerPort:80_connectURLPort:8080_runShoul        dSuccess:true_err:connection_refused}
    run_network_test.go:301: pFlag="127.0.0.1:8080:80", connectURL="http://10.4.0.28:8080"
=== RUN   TestRunPort/{listenIP:[0_0_0_0_0_0_0_0_0_0_255_255_0_0_0_0]_connectIP:[0_0_0_0_0_0_0_0_0_0_255_255_127_0_0_1]_hostPort:8080_containerPort:80_co        nnectURLPort:8080_runShouldSuccess:true_err:}
    run_network_test.go:301: pFlag="0.0.0.0:8080:80", connectURL="http://127.0.0.1:8080"
panic: test timed out after 10m0s

goroutine 783 [running]:
testing.(*M).startAlarm.func1()
        /usr/local/go/src/testing/testing.go:1788 +0x8e
created by time.goFunc
        /usr/local/go/src/time/sleep.go:180 +0x31

goroutine 1 [chan receive, 3 minutes]:
testing.(*T).Run(0xc0004836c0, {0xff996e, 0x46b773}, 0x10543f0)
        /usr/local/go/src/testing/testing.go:1307 +0x375
testing.runTests.func1(0xc00010d1d0)
        /usr/local/go/src/testing/testing.go:1598 +0x6e
testing.tRunner(0xc0004836c0, 0xc00025fc80)
        /usr/local/go/src/testing/testing.go:1259 +0x102
testing.runTests(0xc00033c500, {0x18b93c0, 0x35, 0x35}, {0x17, 0x17, 0x18caac0})
        /usr/local/go/src/testing/testing.go:1596 +0x43f
testing.(*M).Run(0xc00033c500)
        /usr/local/go/src/testing/testing.go:1504 +0x51d
github.com/containerd/nerdctl/pkg/testutil.M(0x101003d1dfed108)
        /go/src/github.com/containerd/nerdctl/pkg/testutil/testutil.go:285 +0x173
github.com/containerd/nerdctl/cmd/nerdctl.TestMain(...)
        /go/src/github.com/containerd/nerdctl/cmd/nerdctl/main_test.go:26
main.main()
        _testmain.go:149 +0x166

goroutine 570 [chan receive, 5 minutes]:
testing.(*T).Parallel(0xc0000dda00)
        /usr/local/go/src/testing/testing.go:1104 +0x1a7
github.com/containerd/nerdctl/cmd/nerdctl.TestRunVolume(0xc0000dda00)
        /go/src/github.com/containerd/nerdctl/cmd/nerdctl/run_mount_test.go:30 +0x3e
testing.tRunner(0xc0000dda00, 0x1054430)
        /usr/local/go/src/testing/testing.go:1259 +0x102
created by testing.(*T).Run
        /usr/local/go/src/testing/testing.go:1306 +0x35a

**Comment by fahedouch** [comment]
Sorry @ningmingxiao  , you issue is not clear. 
Can you detail the steps to reproduce this error?
don't forget to mention the test environment

**Comment by ningmingxiao** [comment]
1. docker build -t test-integration --target test-integration .    to generate   test-integration image
2. tar zxvf nerdctl-full-0.11.2-linux-amd64.tar.gz  -C /usr/local
3.  nerdctl  run -it --rm --privileged=true -v test-integration  instead of  docker run

**Comment by ningmingxiao** [comment]
> Sorry @ningmingxiao , you issue is not clear.
> Can you detail the steps to reproduce this error?
> don't forget to mention the test environment

docker build -t test-integration --target test-integration . to generate test-integration image
tar zxvf nerdctl-full-0.11.2-linux-amd64.tar.gz -C /usr/local
nerdctl run -it --rm --privileged test-integration
will not work like docker
operating system centos7

**Comment by fahedouch** [comment]
Try `nerdctl run -it --rm --privileged --network host test-integration`
